In [115]:
import numpy as np

In [116]:
import pandas as pd

In [117]:
df=pd.read_csv(r'Customer Call List.csv')

In [118]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Unnamed: 8,Unnamed: 9
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,NaN,NaN
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False,NaN,NaN
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,NaN,NaN
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True,NaN,NaN
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,NaN,NaN
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False,NaN,NaN
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False,NaN,NaN
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False,NaN,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True,NaN,NaN
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True,NaN,NaN
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True,NaN,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,NaN,NaN
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False,NaN,NaN
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False,NaN,NaN
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,NaN,NaN
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False,NaN,NaN
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True,NaN,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True,NaN,NaN
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,NaN,NaN
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,NaN,NaN

In [119]:
df=df.drop_duplicates()

In [120]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Unnamed: 8,Unnamed: 9
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,NaN,NaN
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False,NaN,NaN
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,NaN,NaN
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True,NaN,NaN
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,NaN,NaN
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False,NaN,NaN
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False,NaN,NaN
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False,NaN,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True,NaN,NaN
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True,NaN,NaN
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True,NaN,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,NaN,NaN
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False,NaN,NaN
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False,NaN,NaN
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,NaN,NaN
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False,NaN,NaN
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True,NaN,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True,NaN,NaN
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,NaN,NaN

In [121]:
df=df.drop(columns='Not_Useful_Column')

In [122]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Unnamed: 8,Unnamed: 9
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,NaN,NaN
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,NaN,NaN
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,NaN,NaN
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,NaN,NaN
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,NaN,NaN
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,NaN,NaN
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,NaN,NaN
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,NaN,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,NaN,NaN
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,NaN,NaN
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,NaN,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,NaN,NaN
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,NaN,NaN
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,NaN,NaN
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,NaN,NaN
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,NaN,NaN
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,NaN,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,NaN,NaN
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,NaN,NaN

In [123]:
#df['Last_Name']=df['Last_Name'].str.lstrip('...')
#df['Last_Name']=df['Last_Name'].str.lstrip('/')
#df['Last_Name']=df['Last_Name'].str.lstrip('_')
df['Last_Name']=df['Last_Name'].str.strip('123_./')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Unnamed: 8,Unnamed: 9
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,NaN,NaN
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,NaN,NaN
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,NaN,NaN
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,NaN,NaN
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,NaN,NaN
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,NaN,NaN
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,NaN,NaN
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,NaN,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,NaN,NaN
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,NaN,NaN
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,NaN,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,NaN,NaN
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,NaN,NaN
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,NaN,NaN
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,NaN,NaN
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,NaN,NaN
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,NaN,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,NaN,NaN
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,NaN,NaN

In [124]:
df['Phone_Number']=df['Phone_Number'].str.replace('[^a-zA-Z0-9]','')
df

<ipython-input-124-735899cd5341>:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Phone_Number']=df['Phone_Number'].str.replace('[^a-zA-Z0-9]','')

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Unnamed: 8,Unnamed: 9
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No,NaN,NaN
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Yes,NaN,NaN
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,NaN,NaN
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,NaN,NaN
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,No,NaN,NaN
5,1006,Ron,Swanson,3047622467,768 City Parkway,Yes,Yes,NaN,NaN
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,NaN,NaN
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,No,NaN,NaN
8,1009,Gandalf,NaN,Na,123 Middle Earth,Yes,NaN,NaN,NaN
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,No,NaN,NaN
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,NaN,NaN
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,NaN,NaN
12,1013,Don,Draper,1235432345,2039 Main Street,Yes,N,NaN,NaN
13,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,No,NaN,NaN
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,No,NaN,NaN
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N,NaN,NaN
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No,NaN,NaN
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,NaN,NaN
18,1019,Creed,Braton,Na,N/a,N/a,Yes,NaN,NaN
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N,NaN,NaN

In [125]:
df['Phone_Number']=df['Phone_Number'].apply(lambda x: str(x))
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Unnamed: 8,Unnamed: 9
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No,NaN,NaN
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Yes,NaN,NaN
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,NaN,NaN
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,NaN,NaN
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,No,NaN,NaN
5,1006,Ron,Swanson,3047622467,768 City Parkway,Yes,Yes,NaN,NaN
6,1007,Jeff,Winger,nan,1209 South Street,No,No,NaN,NaN
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,No,NaN,NaN
8,1009,Gandalf,NaN,Na,123 Middle Earth,Yes,NaN,NaN,NaN
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,No,NaN,NaN
10,1011,Samwise,Gamgee,nan,"612 Shire Lane, Shire",Yes,No,NaN,NaN
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,NaN,NaN
12,1013,Don,Draper,1235432345,2039 Main Street,Yes,N,NaN,NaN
13,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,No,NaN,NaN
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,No,NaN,NaN
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N,NaN,NaN
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No,NaN,NaN
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,NaN,NaN
18,1019,Creed,Braton,Na,N/a,N/a,Yes,NaN,NaN
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N,NaN,NaN

In [126]:
df['Phone_Number']=df['Phone_Number'].apply(lambda x: x[0:3]+'-'+x[3:6]+'-'+x[6:10])
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Unnamed: 8,Unnamed: 9
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,NaN,NaN
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,NaN,NaN
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,NaN,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,NaN,NaN
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,NaN,NaN
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,NaN,NaN
6,1007,Jeff,Winger,nan--,1209 South Street,No,No,NaN,NaN
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,NaN,NaN
8,1009,Gandalf,NaN,Na--,123 Middle Earth,Yes,NaN,NaN,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,NaN,NaN
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Yes,No,NaN,NaN
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN,NaN,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,NaN,NaN
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,NaN,NaN
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,NaN,NaN
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,NaN,NaN
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,NaN,NaN
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN,NaN,NaN
18,1019,Creed,Braton,Na--,N/a,N/a,Yes,NaN,NaN
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,NaN,NaN

In [127]:
df['Phone_Number']=df['Phone_Number'].str.replace('nan','')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Unnamed: 8,Unnamed: 9
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,NaN,NaN
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,NaN,NaN
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,NaN,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,NaN,NaN
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,NaN,NaN
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,NaN,NaN
6,1007,Jeff,Winger,--,1209 South Street,No,No,NaN,NaN
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,NaN,NaN
8,1009,Gandalf,NaN,Na--,123 Middle Earth,Yes,NaN,NaN,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,NaN,NaN
10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Yes,No,NaN,NaN
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN,NaN,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,NaN,NaN
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,NaN,NaN
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,NaN,NaN
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,NaN,NaN
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,NaN,NaN
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN,NaN,NaN
18,1019,Creed,Braton,Na--,N/a,N/a,Yes,NaN,NaN
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,NaN,NaN

In [128]:
df['Phone_Number']=df['Phone_Number'].str.replace('Na','')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Unnamed: 8,Unnamed: 9
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,NaN,NaN
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,NaN,NaN
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,NaN,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,NaN,NaN
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,NaN,NaN
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,NaN,NaN
6,1007,Jeff,Winger,--,1209 South Street,No,No,NaN,NaN
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,NaN,NaN
8,1009,Gandalf,NaN,--,123 Middle Earth,Yes,NaN,NaN,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,NaN,NaN
10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Yes,No,NaN,NaN
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN,NaN,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,NaN,NaN
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,NaN,NaN
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,NaN,NaN
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,NaN,NaN
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,NaN,NaN
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN,NaN,NaN
18,1019,Creed,Braton,--,N/a,N/a,Yes,NaN,NaN
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,NaN,NaN

In [129]:
df['Phone_Number']=df['Phone_Number'].str.replace('--','')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Unnamed: 8,Unnamed: 9
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,NaN,NaN
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,NaN,NaN
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,NaN,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,NaN,NaN
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,NaN,NaN
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,NaN,NaN
6,1007,Jeff,Winger,,1209 South Street,No,No,NaN,NaN
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,NaN,NaN
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,NaN,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,NaN,NaN
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,NaN,NaN
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN,NaN,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,NaN,NaN
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,NaN,NaN
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,NaN,NaN
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,NaN,NaN
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,NaN,NaN
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN,NaN,NaN
18,1019,Creed,Braton,,N/a,N/a,Yes,NaN,NaN
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,NaN,NaN

In [130]:
df[["Street_Address", "State","Zip_Code"]]=df["Address"].str.split(',',2, expand=True)
df

<ipython-input-130-3ddc7b9615d2>:1: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  df[["Street_Address", "State","Zip_Code"]]=df["Address"].str.split(',',2, expand=True)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Unnamed: 8,Unnamed: 9,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,NaN,NaN,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,NaN,NaN,93 West Main Street,None,None
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,NaN,NaN,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,NaN,NaN,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,NaN,NaN,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,NaN,NaN,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,No,No,NaN,NaN,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,NaN,NaN,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,NaN,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,NaN,NaN,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,NaN,NaN,612 Shire Lane,Shire,None
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN,NaN,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,NaN,NaN,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,NaN,NaN,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,NaN,NaN,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,NaN,NaN,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,NaN,NaN,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN,NaN,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,N/a,Yes,NaN,NaN,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,NaN,NaN,910 Tatooine Road,Tatooine,None

In [131]:
df["Paying Customer"]=df["Paying Customer"].str.replace("Yes","Y")
df["Paying Customer"]=df["Paying Customer"].str.replace("No","N")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Unnamed: 8,Unnamed: 9,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,No,NaN,NaN,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Yes,NaN,NaN,93 West Main Street,None,None
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,NaN,NaN,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,NaN,NaN,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,NaN,NaN,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Yes,NaN,NaN,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,N,No,NaN,NaN,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,NaN,NaN,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Y,NaN,NaN,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,No,NaN,NaN,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,No,NaN,NaN,612 Shire Lane,Shire,None
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN,NaN,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,NaN,NaN,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,No,NaN,NaN,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,NaN,NaN,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,NaN,NaN,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,No,NaN,NaN,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN,NaN,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,N/a,Yes,NaN,NaN,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,NaN,NaN,910 Tatooine Road,Tatooine,None

In [132]:
df["Do_Not_Contact"]=df["Do_Not_Contact"].str.replace("Yes","Y")
df["Do_Not_Contact"]=df["Do_Not_Contact"].str.replace("No","N")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Unnamed: 8,Unnamed: 9,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,NaN,NaN,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,NaN,NaN,93 West Main Street,None,None
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,NaN,NaN,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,NaN,NaN,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,NaN,NaN,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,NaN,NaN,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,N,N,NaN,NaN,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,NaN,NaN,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Y,NaN,NaN,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,NaN,NaN,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,NaN,NaN,612 Shire Lane,Shire,None
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN,NaN,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,NaN,NaN,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,NaN,NaN,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,NaN,NaN,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,NaN,NaN,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,NaN,NaN,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN,NaN,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,N/a,Y,NaN,NaN,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,NaN,NaN,910 Tatooine Road,Tatooine,None

In [133]:
df=df.replace("N/a","")

In [134]:
df=df.fillna("")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Unnamed: 8,Unnamed: 9,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,,,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,,,93 West Main Street,,
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,,,,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,,,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,,,123 Dragons Road,,
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,,,768 City Parkway,,
6,1007,Jeff,Winger,,1209 South Street,N,N,,,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,,,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Y,,,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,,,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,,,612 Shire Lane,Shire,
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,,,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,,,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,,,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,,,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,,,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,,,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,,,,3498 Super Lane,,
18,1019,Creed,Braton,,,,Y,,,,,
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,,,910 Tatooine Road,Tatooine,

In [135]:
for x in df.index:
   if df.loc[x,"Do_Not_Contact"]=="Y":
    df.drop(x, inplace=True)

df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Unnamed: 8,Unnamed: 9,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,,,123 Shire Lane,Shire,
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,,,,298 Drugs Driveway,,
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,,,123 Dragons Road,,
6,1007,Jeff,Winger,,1209 South Street,N,N,,,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,,,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Y,,,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,,,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,,,612 Shire Lane,Shire,
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,,,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,,,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,,,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,,,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,,,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,,,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,,,,3498 Super Lane,,
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,,,910 Tatooine Road,Tatooine,

In [138]:
df["Do_Not_Contact"]=df["Do_Not_Contact"].replace("","N")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Unnamed: 8,Unnamed: 9,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,,,123 Shire Lane,Shire,
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,N,,,298 Drugs Driveway,,
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,,,123 Dragons Road,,
6,1007,Jeff,Winger,,1209 South Street,N,N,,,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,,,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Y,N,,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,,,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,,,612 Shire Lane,Shire,
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,N,,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,,,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,,,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,,,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,,,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,,,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,N,,,3498 Super Lane,,
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,,,910 Tatooine Road,Tatooine,

In [145]:
 #df=df.drop('Address', axis=1)

In [149]:
df=df.reset_index(drop=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Unnamed: 8,Unnamed: 9,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,,,123 Shire Lane,Shire,
1,1003,Walter,White,706-695-0392,N,N,,,298 Drugs Driveway,,
2,1005,Jon,Snow,876-678-3469,Y,N,,,123 Dragons Road,,
3,1007,Jeff,Winger,,N,N,,,1209 South Street,,
4,1008,Sherlock,Holmes,876-678-3469,N,N,,,98 Clue Drive,,
5,1009,Gandalf,,,Y,N,,,123 Middle Earth,,
6,1010,Peter,Parker,123-545-5421,Y,N,,,25th Main Street,New York,
7,1011,Samwise,Gamgee,,Y,N,,,612 Shire Lane,Shire,
8,1012,Harry,Potter,706-695-0392,Y,N,,,2394 Hogwarts Avenue,,
9,1013,Don,Draper,123-543-2345,Y,N,,,2039 Main Street,,
10,1014,Leslie,Knope,876-678-3469,Y,N,,,343 City Parkway,,
11,1015,Toby,Flenderson,304-762-2467,N,N,,,214 HR Avenue,,
12,1016,Ron,Weasley,123-545-5421,N,N,,,2395 Hogwarts Avenue,,
13,1017,Michael,Scott,123-643-9775,Y,N,,,121 Paper Avenue,Pennsylvania,
14,1018,Clark,Kent,706-695-0392,Y,N,,,3498 Super Lane,,
15,1020,Anakin,Skywalker,876-678-3469,Y,N,,,910 Tatooine Road,Tatooine,

In [155]:
#df = df.dropna(axis=1, how='all')
#df

In [165]:
#df.drop(columns="Unnamed: 9")

In [163]:
df=df.drop(columns="Unnamed: 8")

In [164]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,
1,1003,Walter,White,706-695-0392,N,N,298 Drugs Driveway,,
2,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,
3,1007,Jeff,Winger,,N,N,1209 South Street,,
4,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,
5,1009,Gandalf,,,Y,N,123 Middle Earth,,
6,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,
7,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,
8,1012,Harry,Potter,706-695-0392,Y,N,2394 Hogwarts Avenue,,
9,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,
10,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,
11,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,,
12,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,
13,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,
14,1018,Clark,Kent,706-695-0392,Y,N,3498 Super Lane,,
15,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,

In [167]:
df.to_csv('Cleaned_List.csv')